### ISSUE TITLE
S3FS.remove('parent_directory/file') deletes both `file` and `parent_directory` when there is only one file in the directory

### ISSUE THREAD

**Issue by samuelsinayoko** [PyFilesystem/s3fs#4] opened 2017-09-04 11:56 UTC
I've noticed that when there's only one file in a directory, running `botocore.s3.delete_object` deletes both the file and the parent directory. This is unexpected. I've raised an issue on the botocore list https://github.com/boto/botocore/issues/1275 but in the meantime I'd suggest modifying the implementation of `S3FS.remove` to something like
```
    def remove(self, path):
        self.check()
        _path = self.validatepath(path)
        _key = self._path_to_key(_path)
        info = self.getinfo(path)
        if info.is_dir:
            raise errors.FileExpected(path)

        # get around unexpected behaviour in S3
        # whereby deleting the last file in a directory
        # deletes the parent directory as well
        # https://github.com/boto/botocore/issues/1275
        parent = self.delimiter.join(_key.split(self.delimiter)[:-1])
        recreate_parent = len(self.listdir(parent)) == 1
        self.client.delete_object(
            Bucket=self._bucket_name,
            Key=_key
        )
        if recreate_parent:
            try:
                 self.makedir(parent)
            except Exception:  # use a more specific exception here
                 pass

```

**Comment by willmcgugan** [comment] 2017-09-04 13:09
That's annoying! I'll have to think about that one. The `listdir` might be a little inefficient in the code above. What version of boto are you using?

**Comment by samuelsinayoko** [comment] 2017-09-05 08:32
I've been using 
boto3 (1.4.7)
botocore (1.7.3)

**Comment by willmcgugan** [comment] 2017-10-14 09:25
Did you create the file outside of S3FS? There is currently a limitation where S3FS assumes the present of an empty file to indicate a directory. I'm looking in to a more general solution for that.

**Comment by willmcgugan** [comment] 2018-01-31 17:46
I can't reproduce this now. Going to assume it has been fixed in boto!

**Closed by willmcgugan** 2018-01-31 17:46 UTC
Labels: accepted, bug
